export default [
  {
    title: 'Noé',
    titleOriginal: 'Noah',
    langue: 'français',
    langueOriginal: 'anglais',
    vote: '56',
    runtime: '139',
    thumbnail: 'https://images.pexels.com/photos/53483/strawberries-crepe-dessert-sweet-53483.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    director: 'Darren Aronofsky',
    year: '2014',
    genre: [
      'Drame',
      'Aventure',
    ],
    synopsis: "Noé, un père de famille, reçoit un message de Dieu au cours d'un rêve : la Terre s'apprête à subir un déluge apocalyptique, car l'homme a corrompu le monde à force de violence et d'avidité. Il part alors avec sa femme et ses enfants sur le mont Ararat et entreprend la construction d'une arche monumentale pour mettre à l'abri toutes les espèces existantes de l'humanité, sauver les innocents et préserver la vie sur Terre. Il accomplit ainsi son destin hors du commun. Mais il se heurte à un seigneur de la guerre qui cherche à régner sur ce monde dévasté, et qui lance une armée entière contre lui...",
  },
  {
    title: 'Avengers',
    titleOriginal: 'The Avengers',
    langue: 'français',
    langueOriginal: 'anglais',
    vote: '77',
    runtime: '142',
    thumbnail: 'https://images.pexels.com/photos/53483/strawberries-crepe-dessert-sweet-53483.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    director: 'Joss Whedon',
    year: '2012',
    genre: [
      'Science-Fiction',
      'Aventure',
      'Action',
    ],
    synopsis: "Lorsque la sécurité et l’équilibre de la planète sont menacés par un ennemi d’un genre nouveau, Nick Fury, le directeur du SHIELD, l’agence internationale du maintien de la paix, réunit une équipe pour empêcher le monde de basculer dans le chaos. Partout sur Terre, le recrutement des nouveaux héros dont le monde a besoin commence…",
  },
  {
    title: 'Avengers : L\'Ère d\'Ultron',
    titleOriginal: 'Avengers: Age of Ultron',
    langue: 'français',
    langueOriginal: 'anglais',
    vote: '73',
    runtime: '142',
    thumbnail: 'https://images.pexels.com/photos/53483/strawberries-crepe-dessert-sweet-53483.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    director: 'Joss Whedon',
    year: '2015',
    genre: [
      'Science-Fiction',
      'Aventure',
      'Action',
    ],
    synopsis: "Alors que Tony Stark tente de relancer un programme de maintien de la paix jusque-là suspendu, les choses tournent mal et les super-héros Iron Man, Captain America, Thor, Hulk, Black Widow et Hawkeye vont devoir à nouveau unir leurs forces pour combattre le plus puissant de leurs adversaires : le terrible Ultron, un être technologique terrifiant qui s’est juré d’éradiquer l’espèce humaine. Afin d’empêcher celui-ci d’accomplir ses sombres desseins, des alliances inattendues se scellent, les entraînant dans une incroyable aventure et une haletante course contre le temps…",
  },
  {
    title: 'Avengers : Infinity War',
    titleOriginal: 'Avengers: Infinity War',
    langue: 'français',
    langueOriginal: 'anglais',
    vote: '83',
    runtime: '149',
    thumbnail: 'https://images.pexels.com/photos/53483/strawberries-crepe-dessert-sweet-53483.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    director: 'Joe Russo',
    year: '2018',
    genre: [
      'Science-Fiction',
      'Aventure',
      'Action',
    ],
    synopsis: "Les Avengers et leurs alliés devront être prêts à tout sacrifier pour neutraliser le redoutable Thanos avant que son attaque éclair ne conduise à la destruction complète de l’univers.",
  },
];
